version: '3'

services:

  db:
    image: mysql:8.0
    container_name: ${APP_NAME}-db
    volumes:
      - wordpress_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]


  wordpress:
    container_name: ${APP_NAME}-wordpress
    depends_on:
      - db
    build:
      context: ./config/wordpress
      args:
        - SERVER_NAME=${APP_NAME}.local
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:${MYSQL_PORT}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DEBUG=true
    extra_hosts:
      - localhost:172.17.0.1
      - "${APP_NAME}.local:127.0.0.1"
      - host.docker.internal:host-gateway
    hostname: ${APP_NAME}.local
    domainname: local 
    volumes:
      - ./public:/var/www/html:cached


  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: "${APP_NAME}-phpmyadmin"
    restart: unless-stopped
    environment:
      PMA_HOST: db:${MYSQL_PORT}
    ports:
      - ${PHPMYADMIN_PORT}:80
  

  mailpit:
    image: axllent/mailpit:latest
    container_name: "${APP_NAME}-mailpit"
    ports:
      - "1025:1025"
      - "8025:8025"


volumes:
  wordpress_data: {}
